repository root:
  - ./*
  
feature:
  - src/app/Http/**/*

test:
  - src/tests/**/*

good practices:
  - git-hooks/**/*
  - .github/workflows/**/*
  
automation:
  - git-hooks/**/*
  - .github/workflows/**/*
  
code quality:
  - git-hooks/**/*
  - .github/workflows/**/*

composer:
  - src/composer.json
  - composer.json
  
database:
  - src/database/**/*
