version: "3"

networks:
  laravel:
    driver: bridge

services:
  nginx:
    image: nginx:stable-alpine
    container_name: laravel-nginx
    ports:
      - "8088:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel-phpmyadmin
    depends_on:
      - mysql
    external_links:
      - mysql:db
    ports:
      - "9191:80"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      PMA_HOST: mysql
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9009:9000"
    networks:
      - laravel

  swagger-editor:
    container_name: "cygnus-swagger-editor"
    image: swaggerapi/swagger-editor
    restart: "always"
    ports:
      - "8081:8080"

  swagger-ui:
    container_name: "cygnus-swagger-ui"
    image: swaggerapi/swagger-ui
    restart: "always"
    ports:
      - "8082:8080"
    volumes:
      - ./swagger:/usr/share/nginx/html/swagger
    environment:
      SWAGGER_JSON: /swagger/swagger.json
      API_URL: swagger/swagger.json

#Volumes
volumes:
  mysql:
    driver: local