#!/bin/sh

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$")

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

echo "\nValidating PHPCBF:\n"

# Check for phpcs
which ./vendor/bin/phpcbf &> /dev/null
if [[ "$?" == 1 ]]; then
  echo "\t\033[41mPlease install PHPCBF\033[0m"
  exit 1
fi

RULESET=./phpcs.xml

for FILE in $STAGED_FILES
do
  ./vendor/bin/phpcbf --standard="$RULESET" "$FILE"
done

echo "\nPHPCBF fix completed!\n"

exit $?