name: actions
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout develop
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          tools: composer:v2
          php-version: '7.4'

      - name: Install dependencies
        run: cd /src;
             composer install;
             composer update;

      - name: Run unit test
        run: ./vendor/bin/phpunit -c phpunit.xml